---
title: "Difference-in-Differences"
---

# Assignment 10

## Load Data

```{r}
library(tidyverse)

hospitals <- readRDS("~/Documents/TUHH/Casual Data Science for Business Analytics/Causal_Data_Science_Data/hospdd.rds")

```

## Manual Computing

```{r}
# Step 1: Difference between treatment and control group BEFORE treatment
before_control <- hospitals %>%
  filter(hospital >= 19 & hospital<= 46, procedure == 0) %>% 
  pull(satis)
before_treatment <- hospitals %>%
  filter(hospital >= 1 & hospital<=18, procedure == 0) %>% 
  pull(satis)

diff_before <- before_treatment - before_control

# Step 2: Difference between treatment and control group AFTER treatment
after_control <- rep(0, dim(hospitals)[1])
after_treatment <- hospitals %>%
  filter(hospital >= 1 & hospital<=18, procedure == 1) %>% 
  pull(satis)

diff_after <- after_treatment - after_control

diff_diff <- diff_after - diff_before
# sprintf("Estimate: %.2f", diff_diff)
# didn't print it cause its very wrong

```

## Linear Regrression

### month + hospital

```{r}
lm_1 <- lm(satis ~ month + hospital, data = hospitals)
summary(lm_1)

```

### as.factor(month) + as.factor(hospital)

```{r}
lm_2 <- lm(satis ~ as.factor(month) + as.factor(hospital), data = hospitals)
summary(lm_2)
```

### Explanation

I believe I will use the second one with as.factor as it provides estimates for each hospital and also each month rather than all hospitals in all months in the first one.